runtime: nodejs20  # Or any other Node.js version you want to use

entrypoint: node app.js

env_variables:
  NODE_ENV: 'production'

instance_class: F2  # Optional: Adjust the instance class as needed

handlers:
  - url: /static
    static_dir: build/static/
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /.*      # Catch-all handler to route all requests to your Express app
    script: auto